# Pipeline to autodeploy changes

name: Push and Deploy new changes

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
            
            - name: Get SHORT SHA commit
              run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ secrets.AWS_REGION }}
            
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Set up project repository
              working-directory: ./terraform
              run: |
                terraform init
                terraform apply -auto-approve --target=module.ecs.aws_ecr_repository.repo --var "repo-name=${{ secrets.AWS_ECR_REPOSITORY }}"
              
            - name: Build, tag, and push docker image to Amazon ECR
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
                IMAGE_TAG: ${{ env.SHORT_SHA }}
              run: |
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./app
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        